accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns=[
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('mypage/', views.mypage, name='mypage'),
    path('update/', views.update, name='update'),
    path('password/', views.password_change, name='password_change'),
    path('delete/', views.delete, name='delete'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns=[
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/create_comment/', views.create_comment, name='create_comment'),
    path('<int:article_pk>/delete_comment/<int:comment_pk>/', views.delete_comment, name='delete_comment'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser 
# Create your models here.
class User(AbstractUser):
    pass

articles/models.py
from django.db import models
from django.forms import DateField
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.contrib.auth import get_user_model

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    image = ProcessedImageField(blank=True, upload_to='images/', processors=[ResizeToFill(400, 300)], format='JPEG', options={'quality':80})
    created_at = models.DateField(auto_now_add=True)
    upload_at = models.DateField(auto_now=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

class Comment(models.Model):
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'last_name', 'first_name', 'email']

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['last_name', 'first_name', 'email']

accounts/views.py
from email import message
from django.shortcuts import render, redirect
from accounts.forms import CustomUserChangeForm, CustomUserCreationForm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login as auth_login, logout as auth_logout, get_user_model, update_session_auth_hash
from django.contrib import messages
from django.contrib.auth.decorators import login_required

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, '회원가입이 완료되었습니다. 서비스를 이용하려면 로그인해주세요.')
            return redirect('accounts:login')
    else:
        form = CustomUserCreationForm
    context = {
        'form':form
    }
    return render(request, 'accounts/signup.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            messages.success(request, '반갑습니다!')
            return redirect(request.GET.get('next') or 'articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form':form,
    }
    return render(request, 'accounts/login.html', context)

@login_required
def mypage(request):
    context = {
        'articles': request.user.article_set.all(),
        'comments': request.user.comment_set.all(),
    }
    return render(request, 'accounts/mypage.html', context)

@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, '성공적으로 수정되었습니다.')
            return redirect('accounts:mypage')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)

@login_required
def password_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, '비밀번호가 성공적으로 변경되었습니다.')
            return redirect('accounts:mypage')
    else:
        form = PasswordChangeForm(request.POST)
    context = {
        'form':form,
    }
    return render(request, 'accounts/password_change.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('articles:index')

@login_required
def delete(request):
    if request.method == 'POST':
        request.user.delete()
        auth_logout(request)
        messages.success(request, '성공적으로 탈퇴되었습니다.')
        return redirect('accounts:login')
    else:
        messages.warning(request, '잘못된 접근입니다.')
        return redirect('accounts:mypage')

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>로그인</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit">
  </form>
{% endblock content %}

accounts/templates/accounts/mypage.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
  <h1 class='my-5'>마이 페이지</h1>
  <h2>아이디 :
    {{ request.user.username }}</h2>
  <h2 class='my-3'>이름 :
    {{ request.user.last_name }}{{ request.user.first_name }}</h2>
  <h2>E-mail :
    {{ request.user.email }}</h2>
  <div class='d-flex justify-content-end'>
    <a class='btn btn-outline-secondary' href="{% url 'accounts:update' %}">수정</a>
    <button type="button" class="btn btn-outline-danger mx-2" data-bs-toggle="modal" data-bs-target="#exampleModal">
      탈퇴
    </button>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">정말 탈퇴하시겠습니까?</h1>
          </div>
          <div class="modal-body text-danger">
            탈퇴하면 관련된 모든 글이 사라집니다. 괜찮습니까?
          </div>
          <div class="modal-footer">
            <form action="{% url 'accounts:delete' %}" method="POST">
              {% csrf_token %}
              <input class="btn btn-outline-danger" type="submit" value='예'>
            </form>
            <button type="button" class="btn btn-outline-danger" data-bs-dismiss="modal">아니오</button>
          </div>
        </div>
      </div>
    </div>
  </div>
  <h3 class='text-center'>작성한 글({{ request.user.article_set.all.count }})</h3>
  <hr>
  {% for article in articles %}
    <div class='row text-center'>
      <div class='col-6'>
        <a class="text-decoration-none" href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a>
      </div>
      <div class="col-6">
        {{ article.created_at }}
      </div>
    </div>
    <hr>
  {% endfor %}
  <h3 class="mt-5 text-center">작성한 댓글({{ request.user.comment_set.all.count }})</h3>
  <hr>
  {% for comment in comments %}
    <div class='row text-center'>
      <div class='col-6'>
        <a class="text-decoration-none" href="{% url 'articles:detail' comment.article_id %}">{{ comment.content }}</a>
      </div>
      <div class="col-6">
        {{ comment.created_at }}
      </div>
    </div>
    <hr>
  {% endfor %}
{% endblock content %}

accounts/templates/accounts/password_change.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>비밀번호 변경</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit">
  </form>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>회원가입</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit">
  </form>
{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>내 정보 수정</h1>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit">
  </form>
{% endblock content %}