articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns=[
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/create_comment/', views.create_comment, name='create_comment'),
    path('<int:article_pk>/delete_comment/<int:comment_pk>/', views.delete_comment, name='delete_comment'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.forms import DateField
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.contrib.auth import get_user_model

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    image = ProcessedImageField(blank=True, upload_to='images/', processors=[ResizeToFill(400, 300)], format='JPEG', options={'quality':80})
    created_at = models.DateField(auto_now_add=True)
    upload_at = models.DateField(auto_now=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

class Comment(models.Model):
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'content', 'image']
        labels = {
            'title':'제목',
            'content':'내용',
            'image':'첨부파일',
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content' : '댓글',
        }

articles/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from articles.forms import ArticleForm, CommentForm
from articles.models import Article, Comment
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    context = {
        'articles':Article.objects.all()
    }
    return render(request, 'articles/index.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        article_form = ArticleForm(request.POST, request.FILES)
        if article_form.is_valid():
            form = article_form.save(commit=False)
            form.user = request.user
            form.save()
            return redirect ('articles:index')
    else:
        article_form = ArticleForm()
    context = {
        'article_form':article_form,
    }
    return render(request, 'articles/create.html', context)

@login_required
def detail(request, pk):
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm()
    context = {
        'article':article,
        'comment_form':comment_form,
        'comments': article.comment_set.all(),
    }
    return render(request, 'articles/detail.html', context)

@login_required
def update(request, pk):
    article = Article.objects.get(pk=pk)
    if article.user == request.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, request.FILES, instance=article)
            if form.is_valid():
                form.save()
                messages.success(request, '성공적으로 수정되었습니다.')
                return redirect('articles:detail', article.pk)
        else:
            form = ArticleForm(instance=article)
        context = {
            'form':form,
        }
        return render(request, 'articles/update.html', context)
    else:
        messages.warning(request, '잘못된 접근입니다.')
        return redirect('articles:detail', article.pk)

@login_required
def create_comment(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.article = article
            comment.save()
    else:
        messages.warning(request, '잘못된 접근입니다.')    
    return redirect('articles:detail', article.pk)

@login_required
def delete(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST' and article.user == request.user:
        article.delete()
        return redirect('articles:index')

@login_required
def delete_comment(request, article_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.method == 'POST' and (comment.user == request.user):
        comment.delete()
    else:
        messages.warning(request, '잘못된 접근입니다.')
    return redirect('articles:detail', article_pk)

articles/templates/articles/create.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>글 작성</h1>
  <form action="" method="POST" enctype='multipart/form-data'>
    {% csrf_token %}
    {% bootstrap_form article_form %}
    <input type="submit">
  </form>
{% endblock content %}

articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block css %}{% endblock css %}
{% block content %}
  <div class='d-flex justify-content-between mb-5'>
    <h1>{{ article.title }}</h1>
    <div class='d-flex flex-column'>
      <span class='float-end fs-6 fw-light text-secondary'>{{ article.created_at }}</span>
      <span class='float-end fs-6 fw-light text-secondary'>작성자 :
        {{ article.user }}</span>
    </div>
  </div>
  {% if article.image %}
    <img src="{{ article.image.url }}" alt="{{ article.image }}">
  {% endif %}
  <p style='height:10rem;' class='my-3 p-2'>{{ article.content }}</p>
  {% if article.user == request.user %}
    <div class="d-flex justify-content-end">
      <a class='btn btn-secondary mx-2' href="{% url 'articles:update' article.pk %}">수정</a>
      <a class='btn btn-secondary' href="{% url 'articles:delete' article.pk %}">삭제</a>
    </div>
  {% endif %}
  <h3 class='my-3'>{{ comments|length }}개의 댓글</h3>
  <hr>
  {% for comment in comments %}
    <div class='d-flex justify-content-between'>
      <div>
        <p>{{ comment.user }}
          <span style="font-size: .7rem;" class='text-secondary mx-2'>
            {{ comment.created_at }}
          </span>
        </p>
        <p>{{ comment.content }}</p>
      </div>
      {% if comment.user == request.user %}
        <form action="{% url 'articles:delete_comment' article.pk comment.pk %}" method="POST">
          {% csrf_token %}
          <input class='btn btn-outline-danger' type="submit" value="삭제">
        </form>
      {% endif %}
    </div>
    <hr>
  {% endfor %}
  <form action="{% url 'articles:create_comment' article.pk %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form comment_form %}
    <input class='btn btn-outline-secondary' type="submit" value="OK">
  </form>
{% endblock content %}

articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
  <h1 class='mb-3'>게시판</h1>
  <div class="row text-center">
    <div class="col-8 fs-3">글</div>
    <div class="col-2 fs-3">작성자</div>
    <div class="col-2 fs-3">작성날짜</div>
  </div>
  <hr>
  {% for article in articles %}
    <div class="row text-center">
      <div class='col-8'>
        <a class='text-decoration-none' href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a>
      </div>
      <div class='col-2'>{{ article.user }}</div>
      <div class="col-2">{{ article.created_at }}</div>
    </div>
    <hr>
  {% endfor %}
{% endblock content %}

articles/templates/articles/update.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% block content %}
  <h1>update</h1>
  <form action="" method="POST" enctype='multipart/form-data'>
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit">
  </form>
{% endblock content %}