accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns=[
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('mypage/', views.mypage, name='mypage'),
    path('update/', views.update, name='update'),
    path('password/', views.password_change, name='password_change'),
    path('delete/', views.delete, name='delete'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns=[
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/create_comment/', views.create_comment, name='create_comment'),
    path('<int:article_pk>/delete_comment/<int:comment_pk>/', views.delete_comment, name='delete_comment'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@500&display=swap" rel="stylesheet">
    <style>
      body {
        font-family: 'Noto Sans KR', sans-serif;
      }
    </style>
    {% block css %}{% endblock css %}
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-secondary">
      <div class="container-fluid">
        <a class="navbar-brand text-light" href="{% url 'articles:index' %}">게시판</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'articles:create' %}">글 작성</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'accounts:mypage' %}">마이페이지</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'accounts:logout' %}">로그아웃</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'accounts:signup' %}">회원가입</a>
              </li>
              <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'accounts:login' %}">로그인</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
          {{ message }}
        </div>
      {% endfor %}
    {% endif %}
    <div class="container my-5">
      {% block content %}{% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

  </body>

</html>